[2023-07-29T14:30:58.076+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: data_engineering_jobs_dags_v3.write_to_postgres scheduled__2023-02-20T00:00:00+00:00 [queued]>
[2023-07-29T14:30:58.680+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: data_engineering_jobs_dags_v3.write_to_postgres scheduled__2023-02-20T00:00:00+00:00 [queued]>
[2023-07-29T14:30:58.687+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-07-29T14:30:58.699+0000] {taskinstance.py:1284} INFO - Starting attempt 2 of 2
[2023-07-29T14:30:58.700+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-07-29T14:30:59.546+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): write_to_postgres> on 2023-02-20 00:00:00+00:00
[2023-07-29T14:30:59.565+0000] {standard_task_runner.py:55} INFO - Started process 10257 to run task
[2023-07-29T14:30:59.583+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'data_engineering_jobs_dags_v3', 'write_to_postgres', 'scheduled__2023-02-20T00:00:00+00:00', '--job-id', '2326', '--raw', '--subdir', 'DAGS_FOLDER/load_data_v3.py', '--cfg-path', '/tmp/tmp_dxvbp1f']
[2023-07-29T14:30:59.656+0000] {standard_task_runner.py:83} INFO - Job 2326: Subtask write_to_postgres
[2023-07-29T14:31:03.010+0000] {task_command.py:389} INFO - Running <TaskInstance: data_engineering_jobs_dags_v3.write_to_postgres scheduled__2023-02-20T00:00:00+00:00 [running]> on host f1ea17bde741
[2023-07-29T14:31:05.987+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_engineering_jobs_dags_v3
AIRFLOW_CTX_TASK_ID=write_to_postgres
AIRFLOW_CTX_EXECUTION_DATE=2023-02-20T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-02-20T00:00:00+00:00
[2023-07-29T14:31:06.687+0000] {base.py:73} INFO - Using connection ID 'my_connection' for task execution.
[2023-07-29T14:31:07.253+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/load_data_v3.py", line 71, in write_to_postgres
    execute_values(cursor, insert_statement, [tuple(x) for x in df.to_records(index=False)])
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/extras.py", line 1296, in execute_values
    parts.append(cur.mogrify(template, args))
psycopg2.ProgrammingError: can't adapt type 'dict'
[2023-07-29T14:31:07.851+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=data_engineering_jobs_dags_v3, task_id=write_to_postgres, execution_date=20230220T000000, start_date=20230729T143058, end_date=20230729T143107
[2023-07-29T14:31:11.091+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 2326 for task write_to_postgres (can't adapt type 'dict'; 10257)
[2023-07-29T14:31:11.512+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-07-29T14:31:13.409+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
