[2023-07-29T14:35:47.439+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: data_engineering_jobs_dags_v3.write_to_postgres scheduled__2023-03-03T00:00:00+00:00 [queued]>
[2023-07-29T14:35:47.716+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: data_engineering_jobs_dags_v3.write_to_postgres scheduled__2023-03-03T00:00:00+00:00 [queued]>
[2023-07-29T14:35:47.745+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-07-29T14:35:47.783+0000] {taskinstance.py:1284} INFO - Starting attempt 2 of 2
[2023-07-29T14:35:47.784+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-07-29T14:35:48.154+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): write_to_postgres> on 2023-03-03 00:00:00+00:00
[2023-07-29T14:35:48.185+0000] {standard_task_runner.py:55} INFO - Started process 10555 to run task
[2023-07-29T14:35:48.228+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'data_engineering_jobs_dags_v3', 'write_to_postgres', 'scheduled__2023-03-03T00:00:00+00:00', '--job-id', '2370', '--raw', '--subdir', 'DAGS_FOLDER/load_data_v3.py', '--cfg-path', '/tmp/tmpdhu7wqli']
[2023-07-29T14:35:48.308+0000] {standard_task_runner.py:83} INFO - Job 2370: Subtask write_to_postgres
[2023-07-29T14:35:49.192+0000] {task_command.py:389} INFO - Running <TaskInstance: data_engineering_jobs_dags_v3.write_to_postgres scheduled__2023-03-03T00:00:00+00:00 [running]> on host f1ea17bde741
[2023-07-29T14:35:50.715+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_engineering_jobs_dags_v3
AIRFLOW_CTX_TASK_ID=write_to_postgres
AIRFLOW_CTX_EXECUTION_DATE=2023-03-03T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-03T00:00:00+00:00
[2023-07-29T14:35:51.092+0000] {base.py:73} INFO - Using connection ID 'my_connection' for task execution.
[2023-07-29T14:35:51.139+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/load_data_v3.py", line 71, in write_to_postgres
    execute_values(cursor, insert_statement, [tuple(x) for x in df.to_records(index=False)])
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/extras.py", line 1296, in execute_values
    parts.append(cur.mogrify(template, args))
psycopg2.ProgrammingError: can't adapt type 'dict'
[2023-07-29T14:35:51.409+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=data_engineering_jobs_dags_v3, task_id=write_to_postgres, execution_date=20230303T000000, start_date=20230729T143547, end_date=20230729T143551
[2023-07-29T14:35:53.267+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 2370 for task write_to_postgres (can't adapt type 'dict'; 10555)
[2023-07-29T14:35:53.722+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-07-29T14:35:54.057+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
