[2023-07-29T15:13:51.364+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: data_engineering_jobs_dags_v3.write_to_postgres scheduled__2023-06-09T00:00:00+00:00 [queued]>
[2023-07-29T15:13:51.476+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: data_engineering_jobs_dags_v3.write_to_postgres scheduled__2023-06-09T00:00:00+00:00 [queued]>
[2023-07-29T15:13:51.478+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-07-29T15:13:51.547+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 2
[2023-07-29T15:13:51.555+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-07-29T15:13:54.968+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): write_to_postgres> on 2023-06-09 00:00:00+00:00
[2023-07-29T15:13:55.048+0000] {standard_task_runner.py:55} INFO - Started process 12915 to run task
[2023-07-29T15:13:55.186+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'data_engineering_jobs_dags_v3', 'write_to_postgres', 'scheduled__2023-06-09T00:00:00+00:00', '--job-id', '2721', '--raw', '--subdir', 'DAGS_FOLDER/load_data_v3.py', '--cfg-path', '/tmp/tmpw33n2gzj']
[2023-07-29T15:13:55.234+0000] {standard_task_runner.py:83} INFO - Job 2721: Subtask write_to_postgres
[2023-07-29T15:13:56.852+0000] {task_command.py:389} INFO - Running <TaskInstance: data_engineering_jobs_dags_v3.write_to_postgres scheduled__2023-06-09T00:00:00+00:00 [running]> on host f1ea17bde741
[2023-07-29T15:13:59.323+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_engineering_jobs_dags_v3
AIRFLOW_CTX_TASK_ID=write_to_postgres
AIRFLOW_CTX_EXECUTION_DATE=2023-06-09T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-06-09T00:00:00+00:00
[2023-07-29T15:13:59.979+0000] {base.py:73} INFO - Using connection ID 'my_connection' for task execution.
[2023-07-29T15:14:00.269+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/load_data_v3.py", line 71, in write_to_postgres
    execute_values(cursor, insert_statement, [tuple(x) for x in df.to_records(index=False)])
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/extras.py", line 1296, in execute_values
    parts.append(cur.mogrify(template, args))
psycopg2.ProgrammingError: can't adapt type 'dict'
[2023-07-29T15:14:00.678+0000] {taskinstance.py:1327} INFO - Marking task as UP_FOR_RETRY. dag_id=data_engineering_jobs_dags_v3, task_id=write_to_postgres, execution_date=20230609T000000, start_date=20230729T151351, end_date=20230729T151400
[2023-07-29T15:14:01.545+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 2721 for task write_to_postgres (can't adapt type 'dict'; 12915)
[2023-07-29T15:14:01.894+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-07-29T15:14:03.825+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
