[2023-07-29T14:54:14.795+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: data_engineering_jobs_dags_v3.write_to_postgres scheduled__2023-04-17T00:00:00+00:00 [queued]>
[2023-07-29T14:54:14.956+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: data_engineering_jobs_dags_v3.write_to_postgres scheduled__2023-04-17T00:00:00+00:00 [queued]>
[2023-07-29T14:54:14.980+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-07-29T14:54:15.099+0000] {taskinstance.py:1284} INFO - Starting attempt 2 of 2
[2023-07-29T14:54:15.104+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-07-29T14:54:15.996+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): write_to_postgres> on 2023-04-17 00:00:00+00:00
[2023-07-29T14:54:16.023+0000] {standard_task_runner.py:55} INFO - Started process 11726 to run task
[2023-07-29T14:54:16.053+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'data_engineering_jobs_dags_v3', 'write_to_postgres', 'scheduled__2023-04-17T00:00:00+00:00', '--job-id', '2550', '--raw', '--subdir', 'DAGS_FOLDER/load_data_v3.py', '--cfg-path', '/tmp/tmpf0c4vz9q']
[2023-07-29T14:54:16.062+0000] {standard_task_runner.py:83} INFO - Job 2550: Subtask write_to_postgres
[2023-07-29T14:54:17.794+0000] {task_command.py:389} INFO - Running <TaskInstance: data_engineering_jobs_dags_v3.write_to_postgres scheduled__2023-04-17T00:00:00+00:00 [running]> on host f1ea17bde741
[2023-07-29T14:54:19.257+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_engineering_jobs_dags_v3
AIRFLOW_CTX_TASK_ID=write_to_postgres
AIRFLOW_CTX_EXECUTION_DATE=2023-04-17T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-04-17T00:00:00+00:00
[2023-07-29T14:54:19.570+0000] {base.py:73} INFO - Using connection ID 'my_connection' for task execution.
[2023-07-29T14:54:19.821+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/load_data_v3.py", line 71, in write_to_postgres
    execute_values(cursor, insert_statement, [tuple(x) for x in df.to_records(index=False)])
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/extras.py", line 1296, in execute_values
    parts.append(cur.mogrify(template, args))
psycopg2.ProgrammingError: can't adapt type 'dict'
[2023-07-29T14:54:20.214+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=data_engineering_jobs_dags_v3, task_id=write_to_postgres, execution_date=20230417T000000, start_date=20230729T145414, end_date=20230729T145420
[2023-07-29T14:54:20.599+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 2550 for task write_to_postgres (can't adapt type 'dict'; 11726)
[2023-07-29T14:54:20.842+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-07-29T14:54:22.763+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
